---
- name:  enable or disable Remote Assist
  gather_facts: no
  become: no
  hosts: localhost

  collections:
    - purestorage.flasharray

  tasks:
    - name: get FlashArray info
      local_action:
        module: purestorage.flasharray.purefa_info
        fa_url: "{{ my_fa_url }}"
        api_token: "{{ my_api_token }}"
        gather_subset:
          - network
      register: array_info

    - set_fact:
        my_interfaces: []

    - set_fact:
        my_interfaces: "{{ my_interfaces + [item.value.address] }}"
      with_dict: "{{ array_info.purefa_info.network }}"
      when: ( item.value.address != None ) and ( item.value.services | length > 0 ) and ( item.value.services[0] == 'management' )
#      no_log: true

    - name: info
      debug: var=my_interfaces

    - name: Set FlashArray RemoteAssist
      local_action:
        module: purestorage.flasharray.purefa_ra
        fa_url: "{{ item }}"
        api_token: "{{ my_api_token }}"
        state: "{{ state |default('disable') }}"
      register: fa_ra
      with_items: "{{ my_interfaces }}"

#    - name: output
#      debug: var=fa_ra
